CREATE DATABASE IF NOT EXISTS `dust` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_general_ci`;

USE `dust`;

CREATE TABLE IF NOT EXISTS `players`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(16) NOT NULL,
    `uuid` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;