version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  redis:
    image: redis
    networks:
      - banco
  mongo:
    image: mongo
    networks:
      - banco
  maria:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      # Volumes dos dados
      - dados:/var/lib/mysql
      # Scripts
      - ./maria:/maria-scripts
      - ./maria/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  front:
    image: nginx
    volumes:
      # Configuração do Proxy Reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - api
  api:
    image: node
    volumes:
      # Aplicação
      - ./api:/api
    working_dir: /api
    command: bash ./api.sh
    depends_on: 
      - mongo
      - maria
      - redis
    networks:
      - banco
      - web